spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/smartclass
    username: smartclass
    password: smartclass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

server:
  port: 8080

jwt:
  secret: smartclass-super-secret-key-should-be-changed-in-production-2026-08-03
  expiration-ms: 3600000

smartclass:
  database:
    admin:
      host: localhost
      port: 5432
      username: postgres
      password: TON_MOT_DE_PASSE_POSTGRES
      database: postgres
